spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  application:
    name: front-server-1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.241.167:3306/be6_yes255_book
    username: be6_yes255
    password: ${YES25_5_MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  gateway: http://133.186.153.195:8085

nhn:
  appkey: ${NHN_IMAGE_APPKEY}
  secret: ${NHN_IMAGE_SECRET}
naverapi:
  secret: ${NAVER_SECRET}
  id: ${NAVER_ID}

payco:
  client-id: 3RDYkPs3KeIrCYnH9mljM_v
  client-secret: u13B9N3PzPxx7JdQ8qovRelc
  redirect-uri: http://localhost:8040
provider:
  payco:
    authorization-uri: https://id.payco.com/oauth2.0/authorize
    token-uri: https://id.payco.com/oauth2.0/token
    user-info-uri: https://apis-payco.krp.toastoven.net/payco/friends/find_member_v2.json
    user-name-attribute: email