server:
  port: 8040

spring:
  application:
    name: front-server-1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.241.167:3306/be6_yes255_book
    username: be6_yes255
    password: ${YES25_5_MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  gateway: http://localhost:8085

app:
  mode: development
nhn:
  appkey: ${NHN_IMAGE_APPKEY}
  secret: ${NHN_IMAGE_SECRET}
naverapi:
  secret: ${NAVER_SECRET}
  id: ${NAVER_ID}