spring:
  messages:
    basename: messages
    encoding: UTF-8
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  access-token:
    expiration-ms: 18000
    cookie-name: AccessToken
  refresh-token:
    expiration-ms: 8640000
    cookie-name: RefreshToken
  mvc:
    hidden-method:
      filter:
        enabled: true
