server:
  port: 8040

spring:
  application:
    name: front-server-1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.241.167:3306/be6_yes255_book
    username: be6_yes255
    password: ${YES25_5_MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth=true:
          starttls:
            enable=true:

eureka:
  gateway: http://127.0.0.1:8085

app:
  mode: development
nhn:
  appkey: ${NHN_IMAGE_APPKEY}
  secret: ${NHN_IMAGE_SECRET}
naverapi:
  secret: ${NAVER_SECRET}
  id: ${NAVER_ID}

#app:
#  mode: development

payco:
  client-id: 3RDYkPs3KeIrCYnH9mljM_v
  client-secret: u13B9N3PzPxx7JdQ8qovRelc
  redirect-uri: http://test.com:8040/callback
provider:
  payco:
    authorization-uri: https://id.payco.com/oauth2.0/authorize
    token-uri: https://id.payco.com/oauth2.0/token
    logout-uri: https://id.payco.com/oauth2.0/logout


logging:
  level:
    root: debug