spring:
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 3RDYkPs3KeIrCYnH9mljM_v
            client-secret: u13B9N3PzPxx7JdQ8qovRelc
jwt:
  access-token:
    expiration-ms: 18000
    cookie-name: AccessToken
  refresh-token:
    expiration-ms: 8640000
    cookie-name: RefreshToken
  mvc:
    hidden-method:
      filter:
        enabled: true